# Generated by Django 5.2.1 on 2025-06-11 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
